FROM alpine:3.20

ARG KUBECTL_VERSION=v1.30.1

RUN apk add --no-cache \
      bash \
      ca-certificates \
      curl \
      coreutils \
      jq \
      yq \
      skopeo \
    && curl -L -o /usr/local/bin/kubectl \
       "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl" \
    && chmod +x /usr/local/bin/kubectl \
    && kubectl version --client=true
ENV PATH="/usr/local/bin:$PATH"
CMD ["/bin/sh"]
